environment: production

domain: evanbg42.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
website: https://evanbg42.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /personal-site    # place folder name if the site is served in a subfolder

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag